### PR TITLE
Citations to Chat with file

### PR DESCRIPTION
**Pull request by thivy**
This pull request includes a variety of changes to improve the functionality and usability of the codebase. The most important changes include adding a new sheet component to display content in a modal-like interface, adding error handling to the chat menu, improving the code quality and readability of several components, and updating import paths for various components.

Main interface changes:

* <a href="diffhunk://#diff-319e19004d72883ad55ee0b5035771b79f614157b68d255d86a036a1dc78876eR1-R140">`src/components/ui/sheet.tsx`</a>: Added a new sheet component to display content in a modal-like interface.

Chat menu improvements:

* `src/features/chat/chat-menu/menu-items.tsx`: Added error handling to the chat menu and displays error messages using the `useGlobalMessageContext` hook. Changed the `key` prop of the `MenuItem` component to use the index of the mapped array instead of the thread id. (Fa924a70)

Code quality improvements:

* <a href="diffhunk://#diff-43ea6c34859c907a8002fac1a6849e918ff9bf43a10482d915f0beb8dbcb0addL1-R11">`src/components/ui/label.tsx`</a>: Improved code quality and fixed export issue in `Label` component. <a href="diffhunk://#diff-43ea6c34859c907a8002fac1a6849e918ff9bf43a10482d915f0beb8dbcb0addL1-R11">[1]</a> <a href="diffhunk://#diff-43ea6c34859c907a8002fac1a6849e918ff9bf43a10482d915f0beb8dbcb0addL23-R26">[2]</a>
* <a href="diffhunk://#diff-833308ed4183cdb0493ed4c391a973210ff1f2ade37028b2b3ea9ab16b6c1b57L10-R14">`src/components/ui/toaster.tsx`</a>: Minor changes to improve the code quality and readability of `src/components/ui/toaster.tsx`. <a href="diffhunk://#diff-833308ed4183cdb0493ed4c391a973210ff1f2ade37028b2b3ea9ab16b6c1b57L10-R14">[1]</a> <a href="diffhunk://#diff-833308ed4183cdb0493ed4c391a973210ff1f2ade37028b2b3ea9ab16b6c1b57L1-R1">[2]</a> <a href="diffhunk://#diff-833308ed4183cdb0493ed4c391a973210ff1f2ade37028b2b3ea9ab16b6c1b57L30-R34">[3]</a>

Documentation improvements:

* <a href="diffhunk://#diff-8dcbcb36750f4a2b6a41b647b0a834846e7f0900503cb261a105dc5d9d2dda07L22-R24">`src/app/change-log/page.tsx`</a>: Replaced `ReactMarkdown` component with a custom `Markdown` component and updated the file name and location for `update.md`. <a href="diffhunk://#diff-8dcbcb36750f4a2b6a41b647b0a834846e7f0900503cb261a105dc5d9d2dda07L22-R24">[1]</a> <a href="diffhunk://#diff-8dcbcb36750f4a2b6a41b647b0a834846e7f0900503cb261a105dc5d9d2dda07R1-R12">[2]</a>
* <a href="diffhunk://#diff-2914eee07938b14f44d04a3cc5216f310f6e08ae8cb4567a5d4551e9b30e59c9R5-R8">`src/app/change-log/update.md`</a>: Added a new section for citations in the chat with file feature.
* <a href="diffhunk://#diff-b2753e3743a3e61e6cad7a8d015dbf6aa5d3f9a91fa7a290841f0e0fa9d6355fL23-L24">`docs/1-introduction.md`</a>: Removed the `LangChain JS` line from the introduction documentation.

Styling improvements:

* <a href="diffhunk://#diff-29d0a55f5ca1a9951042587f8b891bb4cd8b204f5bc855dc2468ed44cde2f5b3L24-R24">`src/app/layout.tsx`</a>: Added support for light theme by adding the `light` class to the `html` element in `src/app/layout.tsx`.
* <a href="diffhunk://#diff-027a35f5584ceef68685cfaa6d21295fe676501f04e730543d13498cb70b5dd2L7-R10">`src/components/chat/chat-row.tsx`</a>: Replaced the `MemoizedReactMarkdown` component with the `Markdown` component and added the `prose` class for styling in `src/components/chat/chat-row.tsx`. <a href="diffhunk://#diff-027a35f5584ceef68685cfaa6d21295fe676501f04e730543d13498cb70b5dd2L7-R10">[1]</a> <a href="diffhunk://#diff-027a35f5584ceef68685cfaa6d21295fe676501f04e730543d13498cb70b5dd2L82-R85">[2]</a>

Component import updates:

* <a href="diffhunk://#diff-cb58257bfdc48cd922dc056fc88011e9d6893ee5a59e31e19ab431cf87336afcL3-R3">`src/app/chat/layout.tsx`</a>: Updated import path for `MainMenu` component in `src/app/chat/layout.tsx`.
* <a href="diffhunk://#diff-a54d34d7127f7170d7e1313cc7625d78cc7c977e4459e6b4271a6143ef522721L1-R1">`src/app/unauthorized/layout.tsx`</a>: Updated import path and removed whitespace in `src/app/unauthorized/layout.tsx`. <a href="diffhunk://#diff-a54d34d7127f7170d7e1313cc7625d78cc7c977e4459e6b4271a6143ef522721L1-R1">[1]</a> <a href="diffhunk://#diff-a54d34d7127f7170d7e1313cc7625d78cc7c977e4459e6b4271a6143ef522721L1-R1">[2]</a>4R14)
* <a href="diffhunk://#diff-592975e45b53e43ff8f866e4ca30c8a1bc63c84b241251b2faf3b85932294531L1-R1">`src/app/change-log/layout.tsx`</a>: Updated import path for `MainMenu` component in `src/app/change-log/layout.tsx`.
* <a href="diffhunk://#diff-a54d34d7127f7170d7e1313cc7625d78cc7c977e4459e6b4271a6143ef522721L1-R1">`src/app/reporting/layout.tsx`</a>: Updated import statement for `MainMenu` in `src/app/reporting/layout.tsx`.
* <a href="diffhunk://#diff-4588b65e76cf3f248022d4875dc415680e6c4e74ecff0283b27280b84208cfdfL3-R3">`src/features/chat/chat-menu/chat-menu-container.tsx`</a>: Updated import statement for `useMenuContext` in `chat-menu-container.tsx`.
* <a href="diffhunk://#diff-85d76fc85094f8ffb08074f3ccd53b2ce9f5f189025b1369d17b216b228c5fe0L1-L9">`src/components/chat/memoized-react-markdown.tsx`</a>: Replaced the `MemoizedReactMarkdown` component with the `Markdown` component.
* <a href="diffhunk://#diff-a29da83a1ec8becd7eaf5fae5d16265cde27ee0e3ee2d81d8358cbc8906cfd7fR1-R21">`src/components/chat/markdown.tsx`</a>: Added `Markdown` component with dependencies and props.

### CODE REVIEW

**Comment by superpoussin22** [comment]
@thivy 
testing it in my env : I got an error message in logs :
" error_OpenAIError: The OPENAI_API_KEY environment variable is missing or empty; either provide it, or instantiate the OpenAI client with an apiKey option, like new OpenAI({ apiKey: 'My API Key' })."
and the interface no more works : I cant send a prompt to the openai instance.

The main branch is working fine

**Comment by thivy** [comment]
> OPENAI_API_KEY

We added the latest OpenAI JS SDK which requires OPENAI_API_KEY environment variable name. Will update the documentation

https://github.com/openai/openai-node#usage

**Comment by superpoussin22** [comment]
that's clear tnaks @thivy

**Review by davidxw — COMMENTED** [review]
As discussed:
* Update version check logic so that newer versions don't show as out of date
* Group repeating filenames in the citation

**Review by davidxw — APPROVED** [review]

**Pull request merged**
