### PR TITLE
Implements #182: Allow users to edit chat title.

### PR DESCRIPTION
**Pull request by giuliohome**
Implements #182: Allow users to edit chat title

image

### CODE REVIEW

**Comment by giuliohome** [comment]
@microsoft-github-policy-service agree

**Comment by giuliohome** [comment]
Now we are having conflicts because the collapsible menu has been added after I developed this PR 😏 ... the problem I mentioned [here](https://github.com/microsoft/azurechat/issues/183#issue-1913331646)

**Comment by giuliohome** [comment]
@thivy, could you please review this PR before other conflicts might arise? Thanks.

**Comment by KeysAU** [comment]
any progress on this one? pretty handy feature

**Comment by bwitzig-zen** [comment]
@davidxw I think this one can be closed as it was based on the previous UX and the feature was added in later updates.

**Comment by giuliohome** [comment]
I forgot to unsubscribe this so I'm still receiving useless emails about it.

**Pull request closed without merging**
